### ISSUE TITLE
Deadlock appears be caused by write data and discovery entity threads using tcp transport on the writer side.

### ISSUE THREAD

**Issue by chunyisong** [eProsima/Fast-DDS#4203]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Discovering new entities and writing data should not be stucked!

### Current behavior

Deadlock appears be caused by write data and discovery entity threads using tcp transport on the writer side. 

I write a simple test program  [test-dds](https://github.com/chunyisong/test-dds/tree/deadlock-tcp) to reproduce this bug.

To reproduce this bug, open two different consoles: 
In the first one for publisher: ./test-dds pub 
In the second one for subscriber: ./test-dds sub

Then the deadlock will most likely occur.If not writers not stucked,restart second console. 
From console of publisher,_currentMatchedPubs and _totalPubOkDatas log are not changed.
From console of subscriber,_currentMatchedSubs and _totalSubValidDatas logs are alse not changed.

Additionally,other tests produce same stucked dealock:
Change Reliability of writers or readers
Using discovery server (This is actual plan.Here using init peers for simplicity.)
Cmake options to compile fastdds,such is FASTDDS_STATISTICS or STRICT_REALTIME.
Less data leads to a lower probability of deadlock.(such as ./test-dds pub 1 100)
Env: FastDDS 2.13.0 Ubuntu 22.04

### Steps to reproduce

To reproduce this bug, open two different consoles:
In the first one for publisher: ./test-dds pub
In the second one for subscriber: ./test-dds sub

### Fast DDS version/commit

FastDDS v2.13.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

TCPv4

### Additional context

Ubuntu 22/20

### Network traffic capture

![image](https://github.com/eProsima/Fast-DDS/assets/7147583/4dc147aa-cf38-45be-a73f-27cb73e8c1a2)
logs

**Comment by Mario-DL** [comment]
Hi @chunyisong 

Thanks for the report. Could you please check if with the latest release `v2.13.1` the issue persists ? Some improvements were made in `tcp` transport, check the [release notes](https://github.com/eProsima/Fast-DDS/releases/tag/v2.13.1)

**Comment by chunyisong** [comment]
Hi @Mario-DL 

I tested [test-dds](https://github.com/chunyisong/test-dds/tree/deadlock-tcp) with fastdds v2.13.1.Unfortunately,stucked deadlock reappeared! However,with this version, the deadlock is more difficult to trigger.Only starting more subscribers (200 readers per sub) and one publisher(200 writers) and  not killing writers can not reproduce the issue (after about 30 trials of simple test,may be lucky).But following steps  more likely trigger deadlock:
1.  Start discovery server in one console (fast-discovery-server -i 0 -t 10.8.8.6  -q 17480)
2. Edit DEFAULT_FASTRTPS_PROFILES.xml ,change listen port of tcpv4 to 0 ;
3. Start two subscriber(200 readers per sub) in two new consoles (./test-dds sub);
4. Start one publisher (200 writers) in new console (./test-dds pub);
5. Wait 30 seconds and **kill publisher process and restart publisher**,then more likely deadlock may occur (if no deadlock, kill and restart publisher once more),**and write operation are stucked as follows:
![image](https://github.com/eProsima/Fast-DDS/assets/7147583/345b6d3e-04e7-420a-b55c-634380bee5f5)

**Comment by JesusPoderoso** [comment]
Hi @chunyisong, thanks for your report!
We will try to reproduce it in the following weeks and come back to you with some feedback.

**Comment by JesusPoderoso** [comment]
Hi @chunyisong, thanks for your patience.
We've just released Fast DDS v2.14.0 with some TCP improvements and fixes (see [release notes](https://fast-dds.docs.eprosima.com/en/v2.14.0/notes/notes.html)). I think that the `TCPSendResources` cleanup may have fixed your issue. Could you check if it persists, please?

**Comment by chunyisong** [comment]
Sorry for late reply.
I will take some time to test it as soon as possible.
















At 2024-03-21 14:44:07, "Jesús Poderoso" ***@***.***> wrote:

Hi @chunyisong, thanks for your patience.
We've just released Fast DDS v2.14.0 with some TCP improvements and fixes (see release notes). I think that the TCPSendResources cleanup may have fixed your issue. Could you check if it persists, please?

**Comment by chunyisong** [comment]
@JesusPoderoso Sorry for late test.I test fastdds today with [master](https://github.com/eProsima/Fast-DDS/commit/9928d1df72f9bd5e3a85ed9eb25702ea0c5a4ec7) using [same method](https://github.com/eProsima/Fast-DDS/issues/4203#issuecomment-1892141517),the problem still exists.
Below image is one process for a sub,one process for a pub ,one process for discover server,when kill pub process and restart pub immediately.After a while,sub did removed matched writers,but pub  did not.And strangly pub rmoved connection to discovery server!
![image](https://github.com/eProsima/Fast-DDS/assets/7147583/b1691a54-fc8f-49a5-b36e-1936f3e929bb)

**Comment by chunyisong** [comment]
Below image shows two subs on hostA(220.8), a discovery server and tow pubs  on host B(0.202).
1. start 5 process
2. After a minite,kill and immediately restart pub1/pub2/sub1/sub2 one by one as quick as you can.
3. **Then the left most sub and the right most pub actually already are stucked**,even though loging thread still print statistic messages.
5. After a minite,kill the sub and pub in the middle 
6. **Then try to kill discovery server ,but the server stucked and can not kill by ctrl-c**!
7. **Then try to kill stucked pub and sub ,but erver stucked and can not kill by ctrl-c too**!
![1715140996744](https://github.com/eProsima/Fast-DDS/assets/7147583/81f28cb7-91ba-422c-8707-0fff74a0f570)

@JesusPoderoso May be pdp or epd issues.

**Comment by chunyisong** [comment]
@JesusPoderoso Tested with [fastdds 2.14.1](https://github.com/eProsima/Fast-DDS/tree/v2.14.1) today, and deadlock easily appeared.
I tested on localhost with discovery server follows:
1. Start discover server in a console : bin/fast-discovery-server -i 0 -t 127.0.0.1 -q 17480
2. Start two pub processes in two consoles : ./test-dds pub
3. As quickly as you can, start two sub processes in two consoles: ./test-dds sub
4. Unfortunately I met deadlock just during first two tests.Now kill discovery server (ctrl-c) will be stucked.
5. If luckily all processes transfer data normally during a test,then kill discovery server,and after one minite restart it,and deadlock appeared. Now I killed one sub (Not sure which one) then discovery server process ended automatically.

**Comment by JesusPoderoso** [comment]
Hi @chunyisong, thanks for the reproducer!
We are taking a look at it and will bring some feedback.

**Comment by chunyisong** [comment]
@JesusPoderoso According to document of [max_blocking_time](https://fast-dds.docs.eprosima.com/en/v2.14.1/fastdds/dds_layer/publisher/dataWriter/publishingData.html#blocking-of-the-write-operation),writer should return with timeout.
But in fact,writers will always get stucked with the deadlock, and will never return.So, this situation is not in line with the design.

**Comment by wangzm-R** [comment]
![image](https://github.com/eProsima/Fast-DDS/assets/64530666/ae2b8794-d6f2-47e7-b56e-45a00ece7290)

the deadlock stack；

use 2.11.2, if deadlock append, it cannot recover, but use 2.14.0, if a deadlock occurs, then recreate the subscriber， deadlock will exit after about 15 minutes ;

**Comment by wangzm-R** [comment]
> > ![image](https://private-user-images.githubusercontent.com/64530666/335961386-ae2b8794-d6f2-47e7-b56e-45a00ece7290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczOTkyODYsIm5iZiI6MTcxNzM5ODk4NiwicGF0aCI6Ii82NDUzMDY2Ni8zMzU5NjEzODYtYWUyYjg3OTQtZDZmMi00N2U3LWI1NmUtNDVhMDBlY2U3MjkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA3MTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMDYxZGY1YTAyNWU4ZjI0NDNiNzU3YjE2MTJmZGQ5MjhkNGJhOGYwMzFjODEyZDMxNzdjNTE2M2UwMjZhMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fe__vQzsAx4SlOXj2MWFekA4NCnZDgY9TiyoHimSGNk)
> > the deadlock stack；
> > use 2.11.2, if deadlock occurs, it cannot recover, but use 2.14.0, if a deadlock occurs, then recreate the subscriber， deadlock will exit after about 15 minutes ;
> 
> Hi @wangzm-R , did you try v2.14.1?
> 
> My test with v2.14.1 still can not recover until the sucked reader/writer is killed (after that the sucked discover server will recover).

The publisher is on linux, the subscriber is on linux, the subscriber is on the window, when any subscriber device is powered down (the subscriber kill process is invalid), the publisher thread will block until the subscriber restarts;

**Comment by chunyisong** [comment]
Today I test fastdds v2.14.2 with one publisher connected to two subscribers,using 2000 topics, and the deadlock almost always appeared.Also test built-in LARGE-DATA mode and custom larg-data.All attempts have shown no signs of improvement.

Through testing, it is suspected that the problem is occurring at TCP EDP stage.
@JesusPoderoso Has there been any progress on this issue? 
>  [Tested ](https://github.com/chunyisong/test-dds/tree/main)with [fastdds 2.14.1](https://github.com/eProsima/Fast-DDS/tree/v2.14.1) today, and deadlock easily appeared. I tested on localhost with discovery server follows:
> 
> 1. Start discover server in a console : bin/fast-discovery-server -i 0 -t 127.0.0.1 -q 17480
> 2. Start two pub processes  with 200 topics in two consoles : ./test-dds pub
> 3. Start two sub processes  with same 200 topics in sequence as quickly as possible in two consoles: ./test-dds sub
> 4. Unfortunately I met deadlock just during first two tests.Now kill discovery server (ctrl-c) will be stucked.
> 5. If luckily all processes transfer data normally during a test,then kill discovery server,and after one minite restart it,and deadlock appeared. After some minites,I killed specific one pub that published data count was unchanged  then discovery server process ended automatically.
