### ISSUE TITLE
Data race report - potential concurrency issues discovered by dynamic analysis (ANaConDA) [7530]

### ISSUE THREAD

**Issue by od42** [eProsima/Fast-DDS#929]
Hello,

we have applied our dynamic analyser ANaConDA, which looks for issues in concurrency such as data races or deadlocks, on eProsima FAST-RTPS. The reason is that we just wanted to test out our tool. However, perhaps some of the results could be interesting for you. In particular, one of our checkers, which by design produces no false alarms, has reported quite a few data races. We have tried studying the reported code section and related functions from the backtrace, but were unable to determine for sure whether most of the data races are benign or not (i.e. design choices), considering that we dont have a full understanding of eProsima as a whole.

The analysis was performed on FAST-RTPS version 1.9.1 in debug build (git commits - fastrtps: db084b927f7be848145d85fc6df122b5036029b3, fastcdr: tag v1.0.11, fastrtpsgen: tag v1.0.2, foonathan_memory_vendor: v0.3.0). The machine running the analysis was an Ubuntu 18.04.3 virtual machine.
All our analysis (so far) was perfomed by running the fastrtps/examples/C++/HelloWorldExample/HelloWorldExample while analyzing both the publisher and the subscriber.

### 1) ResourceLimitedVector - collection_

A race was detected for these two accesses:
- write at line  81 in file /usr/include/c++/7/bits/vector.tcc
- read  at line 783 in file /usr/include/c++/7/bits/stl_iterator.h

Those were called from eProsima here:
- write at line 353 in file fastrtps/include/fastrtps/utils/collections/ResourceLimitedVector.hpp
- read  at line 293 in file fastrtps/include/fastrtps/utils/collections/ResourceLimitedVector.hpp

Description of the race:
- The race is on a variable called collection_.
- The write was performed in the ensure_capacity() method by calling collection_.reserve(..).
- The read was performed in the iterator begin() method by calling collection_.begin().

This means the collection is being accessed while it is potentialy being resized. The reserve() method of std::vector<..> is not thread-safe as it can reallocate the entire vector. 
	

### 2) RTPSParticipantImpl - mp_builtinProtocols

A race detected for these two accesses:
- write at line  249 in file fastrtps/src/cpp/rtps/participant/RTPSParticipantImpl.cpp
- read  at line 1078 in file fastrtps/src/cpp/rtps/participant/RTPSParticipantImpl.cpp

Description of the race:
- The race in on a variable called mp_builtinProtocols.
- The write was performed in the constructor of RTPSParticipantImpl by assigning a new BuiltinProtocols object.
- The read was performed in the assert_remote_participant_liveliness(..) method in an if statement (mp_builtinProtocols && mp_builtinProtocols->mp_PDP).

This means that an RTPSParticipantImpl object is being accessed before its construction has finished. Its hard to tell what exactly would happen if the assert_remote_participant_liveliness(..) method saw an old value of mp_builtinProtocols, but the body of the if statement influences a trigger timer in the ParticipantProxyData::assert_liveliness() method. This particular trace of the race condition might have no noticable consequences because an inaccurate value of a liveliness trigger timer likely wont be an issue. But its important to note that the RTPSParticipantImpl object is being accessed before its constructor has finished which could cause other issues.

### 3)  WriterProxy - heartbeat_final_flag_:
	
A race was detected for these two accesses:
- write at 374 in file /usr/include/c++/7/bits/atomic_base.h
- read  at 396 in file /usr/include/c++/7/bits/atomic_base.h

Those were called from eProsima here:
- write 486 in file fastrtps/src/cpp/rtps/reader/WriterProxy.cpp
- read  458 in file fastrtps/src/cpp/rtps/reader/WriterProxy.cpp
	
Description:
- The race is on an atomic variable heartbeat_final_flag_.
- The write was performed in the process_heartbeat(..) method by calling the atomic store() method.
- The read was performed in the perform_heartbeat_response() method by calling the atomic load() method.

The process_heartbeat(..) method is only called from the constructor of WriterProxy. This means that a WriterProxy object is being accessed before its construction has finished. In this particular trace of the race condition, the heartbeat_final_flag_ could potentialy be changed from its initial value "false". This might not have any serious consequences depending on what is triggered by the final flag being set to "true". However, it is important to note that the WriterProxy object is being accessed before its constructor has finished which could cause other issues.

   
    
&nbsp;    
&nbsp;   
&nbsp;  

We hope this data race report could be useful for you. I havent included backtraces in the initial post as that would make it a lot longer.  If you'd like to see the backtraces, need any more information, or would like to see even those data races that we consider benign, please feel free to ask.

Best regards,
Ondřej Vašíček
(VeriFIT research group, Brno University of Technology)

**Comment by vincent-hui** [comment]
Hi @od42,

did you analyze 1.9.3 ?

**Comment by od42** [comment]
Hello,

not yet no. I will try, but the analysis takes a long time (possibly weeks) because some of the data races presented have been detected only a very few times (some even just once) out of thousands of executions of the examples. From the nature of our analyser it can be hard to find a data race but it reports no false positives.

**Comment by vincent-hui** [comment]
Hi @od42 ,

Did ANaConDA discover "deadlock between PDP and StatefulReader" ?
https://github.com/eProsima/Fast-RTPS/releases

**Comment by MiguelCompany** [comment]
@od42 Number 2) should have been solved by #980

**Comment by od42** [comment]
Hi @vincent-hui and @MiguelCompany ,

Regarding the mentioned deadlock, We have not performed any deadlock analysis so far. All our focus was on data races only. We will discuss the deadlock detection options we have available and try it out.

And reporting back from analyzing 1.9.3 - So far I have detected all the previous data races except number 2). However, from the nature of dynamic analysis and our analyzer there is no guarantee that the data race is not there anymore. It just means we haven't seen it yet. Our analysis is good for pointing out detected data races, not for verifying their absence. 

I have also detected two new variations of number 1)
##### 1a)
A race was detected for these two accesses:
- write at line 82 in file /usr/include/c++/7/bits/vector.tcc          -- was line 81
- read at line 783 in file /usr/include/c++/7/bits/stl_iterator.h    -- same

Those were called from eProsima here:
- write at line 353 in file fastrtps/include/fastrtps/utils/collections/ResourceLimitedVector.hpp    -- same
- read at line 297 in file fastrtps/include/fastrtps/utils/collections/ResourceLimitedVector.hpp    -- was 293

Looks like the same race as number 1), except that the reading side is collection_.end() instead of collection_.begin()

##### 1b)
A race was detected for these two accesses:
- write at line 102 in file /usr/include/c++/7/bits/vector.tcc        -- was line 81
- read at line 783 in file /usr/include/c++/7/bits/stl_iterator.h    -- same

Those were called from eProsima here:
- write at line 169 in file fastrtps/include/fastrtps/utils/collections/ResourceLimitedVector.hpp    -- was 353
- read at line 297 in file fastrtps/include/fastrtps/utils/collections/ResourceLimitedVector.hpp    -- was 293

The read is from collection_.end() and the write is from collection_.emplace_back(args...). This is a new data race on the ResourceLimitedVector collection_ . A new element is being inserted while another thread is accessing the last element.

**Comment by MiguelCompany** [comment]
Hi @od42 ,

Would you mind to attach the full stacktrace for the data races on ResourceLimitedVector.hpp ? I've been digging a bit and could not find a place where ResourceLimitedVector is accessed without a mutex being locked.

**Comment by od42** [comment]
Hi @MiguelCompany ,

sure here you go. One of them is from 1.9.1 and the rest from 1.9.3 (labeled on the first line). Two for each version of the race, except for the new one because I only have one so far.



[ResourceLimitedVector-realloc-353x293-1.txt](https://github.com/eProsima/Fast-RTPS/files/4147270/ResourceLimitedVector-realloc-353x293-1.txt)
[ResourceLimitedVector-realloc-353x293-2.txt](https://github.com/eProsima/Fast-RTPS/files/4147266/ResourceLimitedVector-realloc-353x293-2.txt)

[ResourceLimitedVector-realloc-353x297-1.txt](https://github.com/eProsima/Fast-RTPS/files/4147267/ResourceLimitedVector-realloc-353x297-1.txt)
[ResourceLimitedVector-realloc-353x297-2.txt](https://github.com/eProsima/Fast-RTPS/files/4147268/ResourceLimitedVector-realloc-353x297-2.txt)

[ResourceLimitedVector-emplace_back-169x297.txt](https://github.com/eProsima/Fast-RTPS/files/4147269/ResourceLimitedVector-emplace_back-169x297.txt)

**Comment by MiguelCompany** [comment]
Hi @od42 

I have analyzed the traces. All of them share a common pattern:

```
Thread 1:
    #2  eprosima::fastrtps::rtps::PDP::add_participant_proxy_data:0x0008730a3 (src/cpp/rtps/builtin/discovery/participant/PDP.cpp:202)
    #3  eprosima::fastrtps::rtps::PDP::initPDP:0x00087396b (src/cpp/rtps/builtin/discovery/participant/PDP.cpp:342)
    #4  eprosima::fastrtps::rtps::PDPSimple::init:0x0008838cf (src/cpp/rtps/builtin/discovery/participant/PDPSimple.cpp:110)
    #5  eprosima::fastrtps::rtps::BuiltinProtocols::initBuiltinProtocols:0x00086cad4 (src/cpp/rtps/builtin/BuiltinProtocols.cpp:120)
    #6  eprosima::fastrtps::rtps::RTPSParticipantImpl::RTPSParticipantImpl:0x0006422e6 (src/cpp/rtps/participant/RTPSParticipantImpl.cpp:253)
    
Thread 2:
    #2  eprosima::fastrtps::rtps::PDP::assert_remote_participant_liveliness:0x0008768cf (src/cpp/rtps/builtin/discovery/participant/PDP.cpp:990)
    #3  eprosima::fastrtps::rtps::RTPSParticipantImpl::assert_remote_participant_liveliness:0x000645e31 (src/cpp/rtps/participant/RTPSParticipantImpl.cpp:1083)
    #4  eprosima::fastrtps::rtps::MessageReceiver::processCDRMsg:0x00062e144 (src/cpp/rtps/messages/MessageReceiver.cpp:347)
    #5  eprosima::fastrtps::rtps::ReceiverResource::OnDataReceived:0x00063e362 (src/cpp/rtps/network/ReceiverResource.cpp:100)
    #6  eprosima::fastdds::rtps::UDPChannelResource::perform_listen_operation:0x0006eb268 (src/cpp/rtps/transport/UDPChannelResource.cpp:66)
```

This happens because a datagram is received and processed (on thread no. 2) while inside the `initBuiltinProtocols` method (on thread #1), so it should also have been solved by #980.

I suggest to check against branch 1.9.x, where the mentioned PR has been merged.

**Comment by od42** [comment]
Hi @MiguelCompany 

I checked out origin/1.9.x in src/fastrtps and clean built eProsima using colcon. And I have detected the race again.

[backtrace.txt](https://github.com/eProsima/Fast-RTPS/files/4152931/backtrace.txt)

**Comment by MiguelCompany** [comment]
Hi @od42 ,

Could you check that #996 fixes the issue?

**Comment by od42** [comment]
Hi @MiguelCompany ,

the race seems to be gone as the analysis has not detected it so far (in over 600 runs now). However, that again doesn't prove that the race is gone (might have just been "unlucky" with the seen program traces).

And number 3) is still present.

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry @od42,

Fast DDS (formerly known as FastRTPS) 1.9.x has reached [end of life](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). The data races reported by your dynamic analyzer might be still present in master. Lately, efforts to fix several data races reported by ThreadSanitizer are being made, so I expect these ones to be solved too. Therefore, I am going to proceed and close this issue. Feel free to reopen it if you can provide us with any new information related to the newest Fast DDS version (the fix could later be backported to the supported branches).
